ports:
  - port: 8080
tasks:
  - init: ./gradlew build
    command: ./gradlew runExamples
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addComment: true
    addBadge: false
    addLabel: prebuilt-in-gitpod
